## 02. Neural Network

Classification is a problem of predicting whether something is one thing or another 
(There can be multiple things as the options)



## 1. Make classification data and get it ready 

In [2]:
import sklearn

In [3]:
from sklearn.datasets import make_circles

# Make 1000 samples

n_samples = 1000

# Create circles 

X, y = make_circles(n_samples, noise= 0.03,
                    random_state=42)


In [4]:
len(X), len(y)

(1000, 1000)

In [5]:
print(X[:5])

[[ 0.75424625  0.23148074]
 [-0.75615888  0.15325888]
 [-0.81539193  0.17328203]
 [-0.39373073  0.69288277]
 [ 0.44220765 -0.89672343]]


In [6]:
print(y[:5])

[1 1 1 1 0]


### 1. Check input and output shapes

In [7]:
X.shape, y.shape

((1000, 2), (1000,))

In [8]:
X

array([[ 0.75424625,  0.23148074],
       [-0.75615888,  0.15325888],
       [-0.81539193,  0.17328203],
       ...,
       [-0.13690036, -0.81001183],
       [ 0.67036156, -0.76750154],
       [ 0.28105665,  0.96382443]])

In [9]:
import torch 
torch.__version__
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(device)

cuda


In [10]:
# View the first example of features and labels

X_sample = X[0]
y_sample = y[0]

print(X_sample,y_sample)
print(X_sample.shape,y_sample.shape)


[0.75424625 0.23148074] 1
(2,) ()


### 1.2 Turn data into tensors and create train and test splits

In [11]:
type(X), X.dtype

(numpy.ndarray, dtype('float64'))

In [12]:
# Turn data into tensors
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)


In [13]:
X[:5],y[:5]
print(X.dtype, y.dtype)

torch.float32 torch.float32


In [15]:
#Split data into training and testing set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                     test_size=0.2,# 0.2 = 20% of data will be test & 80% will be train
                                                     random_state=42 # torch.manual_seed(42)
 
                                                    )

In [16]:
len(X_train), len(X_test), len(y_train), len(y_test)

(800, 200, 800, 200)

## 2. Building model

Lets build a model to classify our blue and red dots.

TODO:

1. setup device
2. construct a model (by subclass nn.module)
3. define loss function and optimizer 
4. create train and test loop

In [18]:
import torch
from torch  import nn

# Step 1. 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

Step 2. Constructing a model.

1. Subclass `nn.module`
2. Create `nn.Linear()` layers that are capable of handling the shapes of our data
3. Define a `forward()` method that outlines the forward pass (or the forward computation) of the model
4. Instantiate and instance of our model class and send it to the target `device`

In [21]:
#1. 
class CircleModelV1(nn.module):
    def __init__(self):
        super().__init__()

        #2. create nn.Linear layers capable of handling the shapes of our data
        self.layer_1 = nn.Linear(in_features=2, 
                                out_features=5) # takes in 2 features and upscale to 5 features.
        self.layer_2 = nn.Linear(in_features=5,# needs to match the out_features of the first layer. 
                                out_features=1)# takes in 5 features from the previous layer and outputs single feature (same shape as y)
    # 3. Define forward method
    def forward(self, x):
        return self.layer_2(self.layer_1(x)) # x-> layer_1 -> layer_2 -> output
    
#4. Instantiate and instance of our model
model_0 = CircleModelV1().to(device)
model_0

AttributeError: module 'torch.nn' has no attribute 'module'