In [44]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

# Intorduction to Tensors

Creating Tensors

In [45]:
#Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [46]:
scaler.ndim
#no diminsions

In [47]:
#Get tesnor back as python int
scaler.item()

7

In [48]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [49]:
vector.ndim

1

In [50]:
vector.shape

torch.Size([2])

In [51]:
# MATRIX

MATRIX = torch.tensor([
    [7,7],
    [4,4]
])
MATRIX


tensor([[7, 7],
        [4, 4]])

In [52]:
MATRIX.ndim

2

In [53]:
MATRIX.shape

torch.Size([2, 2])

In [54]:
MATRIX[1]

tensor([4, 4])

In [55]:
MATRIX[0]

tensor([7, 7])

In [56]:
#TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [1,3,5],
    [1,5,8]
                       ]])

TENSOR

tensor([[[1, 2, 3],
         [1, 3, 5],
         [1, 5, 8]]])

In [57]:
TENSOR.size()

torch.Size([1, 3, 3])

In [58]:
TENSOR.shape

torch.Size([1, 3, 3])

In [59]:
TENSOR[0]
# For Further Informations visit https://www.learnpytorch.io/00_pytorch_fundamentals/

tensor([[1, 2, 3],
        [1, 3, 5],
        [1, 5, 8]])

# Creating Random Tensors 

In [60]:
random = torch.rand(size=(3,3))
random

tensor([[0.6962, 0.8479, 0.4773],
        [0.1668, 0.7553, 0.9557],
        [0.2821, 0.5514, 0.9733]])

# Create a range of Tensors and Tensors-Like

In [61]:
#Use Torch.Range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
torch.__version__

'2.0.1+cu117'

In [63]:
#Creating tensor like
ten_zeroes = torch.zeros_like(one_to_ten)

ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
#random tensor-like --> torch.rand is only implemented for float types 
zeroes = torch.zeros(5,4)
random_like = torch.rand_like(input=zeroes)
random_like

tensor([[0.7944, 0.5116, 0.1976, 0.0744],
        [0.7776, 0.0200, 0.7016, 0.1118],
        [0.9812, 0.6231, 0.5577, 0.1963],
        [0.7903, 0.1584, 0.8325, 0.3872],
        [0.7045, 0.1778, 0.9246, 0.0734]])

# Tensor DataTypes

**Note** Tensor datatypes is one of the 3 big errors you will run into with PyTorch
& deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

https://pytorch.org/docs/stable/tensors.html#data-types

Precision in computing:
https://en.wikipedia.org/wiki/Precision_(computer_science)


In [65]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False) # THESE ARE THE THREE IMPORTANT PARAMS

float_32_tensor

tensor([3., 6., 9.])

In [66]:
float_32_tensor.dtype

torch.float32

In [67]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [68]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [69]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [70]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

# Getting information from tensors

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [71]:
#get data-type
print(f"DataType of tensor: {float_16_tensor.dtype}")

DataType of tensor: torch.float16


In [72]:
# get shape
print(f"Shape of tensor: {float_16_tensor.shape}")

Shape of tensor: torch.Size([3])


In [73]:
#get device
print(f"Device tensor on : {float_16_tensor.device}")

Device tensor on : cpu


# Manipulating Tensors ( Tensor operations )

Tensor operations include:
* Addition
* Subtractions
* Multiplication (element-wise)
* Division 
* Matrix multiplication

In [74]:
#create a tensor & add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [75]:
#Multiply Tensors by 10
tensor * 10 

tensor([10, 20, 30])

In [76]:
#Subtractions
tensor - 10

tensor([-9, -8, -7])

In [77]:
#Try Pytorch in-build functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [78]:
torch.add(tensor,5)

tensor([6, 7, 8])

# Matrix Multiplication

Two main ways of performing multipication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work.
* `(2,3) @ (3,2)` will work.
* `(3,2) @ (2,3)` will work.

2. The resulting matrix has the shape of the **Outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [79]:
#Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [80]:
#1
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [81]:
#2
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8402, 0.6963],
        [0.8760, 0.5547]])

In [82]:
#The resulting matrix has the shape of the Outer dimensions
torch.matmul(torch.rand(8,10), torch.rand(10,8)).shape

torch.Size([8, 8])

In [83]:
#Matrix multiplication (dot product)
%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

# One of the most common errors in deep learning: Shape errors

In [84]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                [3,4],
                [5,6]])

tensor_B = torch.tensor([[7,10],
                [8,11],
                [9,12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [85]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**.


A **Transpose** switches the axes or dimensions of a given tensor


In [86]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [87]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [88]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [89]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [90]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
output= torch.mm(tensor_A , tensor_B.T)
print("Output:\n")
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


# Finding the min, max, mean, sum, etc (tensor aggregation) 

In [91]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [92]:
#find the min
x.min()

tensor(0)

In [93]:
#find the max
x.max()

tensor(90)

In [94]:
#find the mean - note: the torch.mean() requires the tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [95]:
#find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [96]:
tensor_Y = torch.rand(4,4)
tensor_Y

tensor([[0.1885, 0.0221, 0.5210, 0.4915],
        [0.6118, 0.9362, 0.4900, 0.0218],
        [0.8083, 0.1835, 0.8579, 0.9563],
        [0.4181, 0.5232, 0.3205, 0.4938]])

In [97]:
torch.argmin(tensor_Y) #Returns the indices of the minimum value(s) of the flattened tensor or along a dimension

tensor(7)

In [98]:
torch.argmax(x) #Returns the indices of the maximum value of all elements in the input tensor.

tensor(9)

In [99]:
x.argmax()

tensor(9)